project:
  type: book
  output-dir: docs

bibliography: ../../myBiber.bib
cls: apa-6th-edition.cls

book:
  title: "Introduction to Psychological Statistics"
  subtitle: "Hands-On Exercises with R/RStudio for Beginners"
  author:
  - name: "Koji Kosugi"
    orcid: 0000-0001-5816-0099
    email: classkosugitti@gmail.com
  page-navigation: true
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  cover-image: cover.png
  date: ""
  chapters:
    - index.qmd
    - chapter01.qmd
    - chapter02.qmd
    - chapter03.qmd
    - chapter04.qmd
    - chapter05.qmd
    - chapter06.qmd
    - chapter07.qmd
    - chapter08.qmd
    - chapter09.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
    - chapter13.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    dev: ragg_png
  pdf:
    documentclass: book
    pdf-engine: lualatex
    papersize: a4
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    cite-method: biblatex
    colorlinks: true
  epub:
    cover-image: cover.png

