project:
  type: book
  output-dir: docs

book:
  title: "心理学統計演習"
  author: "Koji Kosugi"
  page-navigation: true
  date: ""
  chapters:
    - index.qmd
    - chapter01.qmd
    - chapter02.qmd
    - chapter03.qmd
    - chapter04.qmd
    - chapter05.qmd
    - chapter06.qmd
    - chapter07.qmd
    - chapter08.qmd
    - chapter09.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
    - chapter13.qmd

bibliography: reference.bib
cls: apa-6th-edition.cls

format:
  html:
    theme: cosmo
  pdf:
    documentclass: ltjsbook
    pdf-engine: lualatex
    papersize: a4
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    cite-method: biblatex
    colorlinks: true
    keep-tex: true
    mainfont: "Hiragino Sans GB"
  epub:
    keep-md: true
    cover-image: cover.png
