project:
  type: book
  output-dir: docs

book:
  title: "心理学統計演習"
  author: "Koji Kosugi"
  page-navigation: true
  date: ""
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - chapter7.qmd
    - chapter8.qmd
    - chapter9.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
  appendices:
    - chapter1.qmd
    - chapter2.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: ltjsbook
    pdf-engine: lualatex
    papersize: a4
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    cite-method: biblatex
    colorlinks: true
    keep-tex: true
    mainfont: "Hiragino Sans GB"
  epub:
    keep-md: true
    cover-image: cover.png
