<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Psychological Statistics - 7&nbsp; Statistical Hypothesis Testing (Null Hypothesis Statistical Testing)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter08.html" rel="next">
<link href="./chapter06.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter07.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Hypothesis Testing (Null Hypothesis Statistical Testing)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Psychological Statistics</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Introduction-to-Psychological-Statistics.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Introduction-to-Psychological-Statistics.epub">
              <i class="bi bi-bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Let’s Start with R/RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentals of R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Handling with R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Creating Reports with R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Programming with R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability and Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter07.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Hypothesis Testing (Null Hypothesis Statistical Testing)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Testing for Difference in Means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Test of the Difference in Mean Values of Multiple Groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simulation of Null Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Basics of Regression Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Expanding Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduction to Multivariate Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-logic-and-procedures-of-null-hypothesis-testing" id="toc-the-logic-and-procedures-of-null-hypothesis-testing" class="nav-link active" data-scroll-target="#the-logic-and-procedures-of-null-hypothesis-testing"><span class="header-section-number">7.1</span> The Logic and Procedures of Null Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#the-purpose-of-null-hypothesis-testing" id="toc-the-purpose-of-null-hypothesis-testing" class="nav-link" data-scroll-target="#the-purpose-of-null-hypothesis-testing"><span class="header-section-number">7.1.1</span> The Purpose of Null Hypothesis Testing</a></li>
  <li><a href="#procedure-for-null-hypothesis-testing" id="toc-procedure-for-null-hypothesis-testing" class="nav-link" data-scroll-target="#procedure-for-null-hypothesis-testing"><span class="header-section-number">7.1.2</span> Procedure for Null Hypothesis Testing</a></li>
  </ul></li>
  <li><a href="#testing-the-correlation-coefficient" id="toc-testing-the-correlation-coefficient" class="nav-link" data-scroll-target="#testing-the-correlation-coefficient"><span class="header-section-number">7.2</span> Testing the Correlation Coefficient</a></li>
  <li><a href="#distribution-and-testing-of-sample-correlation-coefficients" id="toc-distribution-and-testing-of-sample-correlation-coefficients" class="nav-link" data-scroll-target="#distribution-and-testing-of-sample-correlation-coefficients"><span class="header-section-number">7.3</span> Distribution and Testing of Sample Correlation Coefficients</a></li>
  <li><a href="#probability-of-errors-in-two-types-of-tests" id="toc-probability-of-errors-in-two-types-of-tests" class="nav-link" data-scroll-target="#probability-of-errors-in-two-types-of-tests"><span class="header-section-number">7.4</span> Probability of Errors in Two Types of Tests</a></li>
  <li><a href="#practice-problems-an-example-of-correlation-test" id="toc-practice-problems-an-example-of-correlation-test" class="nav-link" data-scroll-target="#practice-problems-an-example-of-correlation-test"><span class="header-section-number">7.5</span> Practice Problems: An Example of Correlation Test</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Statistical Hypothesis Testing (Null Hypothesis Statistical Testing)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Null hypothesis testing is likely a representative scene of using statistics in psychology. These procedures are formalized, and some statistical packages can automatically provide results just by specifying the type of data. It has the significant advantage of yielding the same results for anyone who carries out the procedures and allowing for automation of these procedures. Its downside, however, is that beginners might obtain erroneous results without fully understanding the mechanisms, or malicious users could manipulate the results to their advantage. Scientific endeavors don’t typically anticipate malevolent practitioners, and if such misconduct emerges, the only recourse is to expose and address it after the fact. Regrettably, we often see careless mistakes and unintended misuse among beginners.</p>
<p>In psychology, the failure to replicate the results of previous studies is referred to as the replication crisis, one cause of which is considered to be the improper use of statistical methods <span class="citation" data-cites="Ikeda2016">(<a href="#ref-Ikeda2016" role="doc-biblioref">池田 and 平石 2016</a>)</span>. Let’s take a moment to revisit and carefully examine the procedures and logic behind null hypothesis testing.</p>
<section id="the-logic-and-procedures-of-null-hypothesis-testing" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="the-logic-and-procedures-of-null-hypothesis-testing"><span class="header-section-number">7.1</span> The Logic and Procedures of Null Hypothesis Testing</h2>
<section id="the-purpose-of-null-hypothesis-testing" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="the-purpose-of-null-hypothesis-testing"><span class="header-section-number">7.1.1</span> The Purpose of Null Hypothesis Testing</h3>
<p>The null hypothesis testing is a framework used to determine whether the findings obtained from the data collected through experiments or surveys carry any significance, and whether these can be generalized as characteristics of the population. It can be thought of as a kind of game with explicit methods and criteria. That’s because null hypothesis testing involves a showdown between two models (approaches) known as the “null hypothesis” and the “alternative hypothesis,” using a criterion called the “significance level” to determine the victor. The reason we use terms like victories or defeats is that the null hypothesis and the alternative hypothesis are in an exclusive relationship - it won’t end in a conclusion where both are correct or both are wrong. However, we must remember, since the judgments are based on stochastic statistical logic, the results also involve elements of probability. The likelihood of erroneously adjudging the alternative hypothesis as right when the null hypothesis is, in fact, correct is not nil. Conversely, there is also a chance of wrongly ruling that the alternative hypothesis is incorrect (or the null hypothesis is correct) when in reality the null hypothesis is not correct. The former is known as a “Type 1 Error”, and the latter as a “Type 2 Error”. While we would like both these probabilities to be zero, that’s not how it turns out, so when we denote Type 1 error as <span class="math inline">\(\alpha\)</span> and Type 2 error as <span class="math inline">\(\beta\)</span>, we aim to keep both under a certain level. The null hypothesis testing was generalized and regulated procedure for this purpose. The aforementioned significance level is the allowable level for this <span class="math inline">\(\alpha\)</span>, which is commonly set at 5% in psychology.</p>
<p>Thus, the concept of null hypothesis testing is fundamentally misguided by the idea of “manipulating to become significant,” as the original intention is to control errors. Moreover, since statistical estimation is a mathematical procedure combined with a human intervention to make judgments that are easy for humans to accept, care should be taken not to attach excessive meaning to the results of null hypothesis testing or to become overly excited or discouraged by them.</p>
</section>
<section id="procedure-for-null-hypothesis-testing" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="procedure-for-null-hypothesis-testing"><span class="header-section-number">7.1.2</span> Procedure for Null Hypothesis Testing</h3>
<p>When we generalize the procedure for null hypothesis testing, it becomes as follows.</p>
<ol type="1">
<li>Setting up the null hypothesis and alternative hypothesis.</li>
<li>Choose a Test Statistic.</li>
<li>Establishing the criteria for judgement.</li>
<li>Calculate the test statistic.</li>
<li>Make a decision.</li>
</ol>
<p>Null hypothesis testing is applied to instances to determine whether there is a difference in the mean values between groups or whether there is statistical significance in the correlation coefficients. Of course, this discussion is about estimating a population from a sample, and does not pertain to contexts such as theoretically judging the truth in physics, or instances where information of the entire population is available, like a census. Additionally, let’s remind ourselves that the sample size is small and the confidence interval of the sample statistic is large, which means it cannot be determined without a framework.</p>
<p>As we cannot understand the state of the population, we set up a hypothesis. The Null Hypothesis reflects the idea of an “empty” hypothesis, stating that there is no mean difference (the difference is zero, <span class="math inline">\(\mu_1 - \mu_2 = 0\)</span>) or the population correlation is zero (<span class="math inline">\(\rho = 0\)</span>). The Alternative Hypothesis is created as a hypothesis that has an exclusive relationship with the Null Hypothesis, hence it is expressed in terms like “there is not no difference (<span class="math inline">\(\mu_1 - \mu_2 \neq 0\)</span>)” and “the correlation is not zero (<span class="math inline">\(\rho \neq 0\)</span>)”.</p>
<p>You may wonder why we start with the Null Hypothesis being zero. This is because when we think about two exclusive hypotheses, there are countless situations in which the state is not zero, so it cannot be specifically asserted as a hypothesis (it wouldn’t make sense to keep testing it indefinitely when the difference is 1, 1.1, 1.11, and so on).</p>
<p>The selection of test statistics is generally presented in a given manner, such as using ‘t’ for the difference in mean values between two groups, ‘F’ for three or more groups, and ‘t’ for testing correlation coefficients. These statistics are selected based on mathematical and statistical evidence. It’s common to use a threshold of a 5% level for deciding. As the calculation of test statistics can be mechanically done according to algorithms, decisions are made based on objective indicators. Consequently, if we can categorize “what null hypothesis should be set in which situation”, then this entire procedure can be carried out automatically.</p>
<p>However, let’s take a careful look at the process again here, following each step meticulously.</p>
</section>
</section>
<section id="testing-the-correlation-coefficient" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="testing-the-correlation-coefficient"><span class="header-section-number">7.2</span> Testing the Correlation Coefficient</h2>
<p>We will look at the test of the correlation coefficient, commonly referred to as the “correlation absence test.” Instead of checking how big the correlation is or how significant it is, we check if it’s not uncorrelated. Of course, if the sample correlation is calculated and isn’t zero, then it’s not uncorrelated. What we want to consider here is that the population correlation is not zero. In other words, even if the population correlation is in a state of zero, the fact that the sample correlation isn’t zero is a natural thing under the context of sampling a small sample.</p>
<p>Let’s check it out. First, consider creating an uncorrelated dataset. Use the <code>MASS</code> package in R, and generate random numbers from the probability distribution function of a multivariate normal distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">mvrnorm</span>(N,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sigma =</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>), <span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">empirical =</span> <span class="cn">TRUE</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]        [,2]
[1,] -0.4070308 -0.72271139
[2,] -0.5774631 -0.57075167
[3,]  0.2312929 -0.42458994
[4,]  0.6242499 -0.55522146
[5,] -0.7791585  0.55004824
[6,]  1.8995860 -0.04899946</code></pre>
</div>
</div>
<p>We have generated 10^{5} random numbers here. The object <code>X</code> that we created consists of two variables, as shown. The assumption here is that we are working with two variables that are correlated and follow a standard normal distribution. One could use the <code>rnorm</code> function twice to create the two variables but considering that we would derive them as a two-variable set, it leads us to contemplate a multivariate normal distribution. The multivariate normal distribution has a mean and standard deviation (SD) for each individual variable and also possesses covariance for variable combinations. Looking at the arguments for <code>mvrnorm</code>, <code>mu</code> represents a mean vector and <code>Sigma</code> is the variance-covariance matrix. Here, the variance-covariance matrix is a <span class="math inline">\(2 \times 2\)</span> square matrix, where diagonal elements represent variance and off-diagonal elements represent covariance. Covariance is expressed as the product of standard deviation and correlation coefficient.</p>
<p><strong>Variance</strong></p>
<p>The above formula calculates the variance, denoted as ( s_x^2 ), for a given set of data. It is calculated by summing the squares of the differences between each data point ( x_i ) and the mean of the data set ( {x} ). This sum is then divided by the number of data points, ( n ), to calculate the variance. This average of squared differences from the mean represents how spread out the data is. As you can see, each difference ( (x_i - {x}) ) is squared before being summed to ensure all differences are treated as positive values.</p>
<p><strong>Standard Deviation</strong></p>
<p>This equation represents the standard deviation (s_x), which is derived from the square root of variance (s_x²). The variance is calculated by summing up the squared differences between each observation in a dataset (represented as x_i) and the mean of the dataset (represented as x̄), and then dividing this total by the number of observations in the dataset (represented as n).</p>
<p><strong>Covariance</strong></p>
<p>This formula calculates the covariance between two variables. In this equation, “s_xy” represents the covariance of the variables x and y. The summation sign Σ (sum) is used to add together the products of each pair of corresponding elements in the x and y data sets. “x_i” and “y_i” are the individual data points in the variables x and y, while “n” signifies the total number of data points. The terms “{x}” and “{y}” denote the means of the x and y variables respectively.</p>
<p>This measurement of covariance allows us to understand and quantify the relationship between two variables. A positive covariance indicates that the two variables tend to increase or decrease together, while a negative covariance suggests that one variable tends to increase when the other decreases.</p>
<p><strong>Correlation Coefficient</strong></p>
<p>The formula above is for computing the correlation coefficient (r_xy) between two variables, x and y. The correlation coefficient, often denoted as r, measures the strength and direction of a linear relationship between two variables. It’s a unit-less measure ranging from -1 to +1, where -1 suggests a perfect negative linear relationship and +1 indicates a perfect positive linear relationship.</p>
<p>Let’s break down this formula:</p>
<ul>
<li><span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span> are the individual sample points indexed with i.</li>
<li><span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span> represent the mean (average) of the x and y variables.</li>
<li><span class="math inline">\(s_{xy}\)</span>, in the numerator, is the covariance of x and y, which is the average of the product of their deviations from their respective means.</li>
<li><span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span>, in the denominator, represent the standard deviations of x and y respectively. The standard deviation is a measure of how spread out the numbers are from their average value, larger values indicating more variability.</li>
</ul>
<p>In sum, the correlation coefficient equals the covariance of x and y divided by the product of their standard deviations.</p>
<p>Learning and implementing such statistical calculations in R and RStudio will give you a better understanding and control over your data analysis process, helping you tease out meaningful patterns and relationships. These tools allow us to perform complex statistics with ease, alleviating the manual math work seen above. But understanding the underlying math continually lays the foundation for deeper and more insightful analysis.</p>
<p><strong>Variance-Covariance Matrix</strong></p>
<p><span class="math display">\[\Sigma = \begin{pmatrix} s_x^2 &amp; s_{xy} \\ s_{yx} &amp; s_y^2 \end{pmatrix}
\end{document}\]</span></p>
<p>This formula expresses a covariance matrix. In this matrix:</p>
<p><span class="math inline">\(s_x^2\)</span> represents the variance of X, <span class="math inline">\(s_y^2\)</span> stands for the variance of Y, <span class="math inline">\(s_{xy}\)</span> and <span class="math inline">\(s_{yx}\)</span> denote the covariance between X and Y.</p>
<p>Variance is a measure that exhibits how much a set of values spreads out, while covariance provides insight into how much two variables vary together. These values play a crucial role in various statistical operations and analyses. You didn’t provide any Japanese text to translate into English. If you need to translate something, please provide the Japanese text.</p>
<p>The reason for using <code>Sigma = matrix(c(1,0,0,1),ncol = 2)</code> is to state that these two variables are uncorrelated and that their standard deviations are each 1. By the way, the option <code>empirical = TRUE</code> means it will adjust the generated random numbers to match the correlation coefficient of the variance-covariance matrix that has been set.</p>
<p>Let’s visualize this. We will verify that the created random numbers are uncorrelated by using a scatter diagram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ dplyr::select() masks MASS::select()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>X <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> V1, <span class="at">y =</span> V2)) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter07_files/figure-html/ggR-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Let’s also verify this numerically.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(X) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    1    0
[2,]    0    1</code></pre>
</div>
</div>
<p>We have confirmed that the generated random numbers are uncorrelated. Now, assuming this is the population, let’s say we take a sample of <code>n = 20</code> from here. What would the correlation be at this time? Let’s do some calculations using R. Decide which rows to extract using the <code>sample</code> function, and assign only the corresponding rows to the <code>s1</code> object. Then let’s try calculating the correlation coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>selected_row <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>N, <span class="dv">20</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(selected_row)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  9647 80702 57543 93179 99032 82624 32672 53670 69698 42383 23801 69303
[13]  9816 61803 69464 23107 76958 44447    10 27292</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> X[selected_row, ]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(s1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]      [,2]
[1,] 1.0000000 0.1431698
[2,] 0.1431698 1.0000000</code></pre>
</div>
</div>
<p>The correlation coefficient this time turned out to be 0.1431698. Even if the population correlation is 0, it’s possible for a randomly selected 20 points to have a correlation coefficient (not 0). The question is, to what extent is this possible? In other words, if a researcher obtains a correlation using a sample of <span class="math inline">\(n=20\)</span> and it turns out to be <span class="math inline">\(r = 0.14\)</span>, how likely is it that the sample came from a population correlation of <span class="math inline">\(\rho = 0.0\)</span>?</p>
</section>
<section id="distribution-and-testing-of-sample-correlation-coefficients" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="distribution-and-testing-of-sample-correlation-coefficients"><span class="header-section-number">7.3</span> Distribution and Testing of Sample Correlation Coefficients</h2>
<p>The sample correlation coefficient is a random variable, so its value changes each time a sample is taken, and the degree to which each value appears can be represented by the sample distribution. So, what kind of sampling distribution might we follow? Let’s try to approximate it by repeating the previous sampling and through the use of random numbers<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>iter <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>iter) {</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  selected_row <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>N, <span class="dv">20</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  s_i <span class="ot">&lt;-</span> X[selected_row, ]</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  cor_i <span class="ot">&lt;-</span> <span class="fu">cor</span>(s_i)[<span class="dv">1</span>, <span class="dv">2</span>]</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  samples <span class="ot">&lt;-</span> <span class="fu">c</span>(samples, cor_i)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">R =</span> samples)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># ヒストグラムの描画</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> R)) <span class="sc">+</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.01</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter07_files/figure-html/sampleDist-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>When we examine the histogram, it can be seen that even in instances where the population correlation coefficient <span class="math inline">\(\rho = 0.0\)</span> and the sample size is 20, sample correlations around <span class="math inline">\(r = 0.3\)</span> or <span class="math inline">\(r = 0.4\)</span> can still occur to a certain extent.</p>
<p>Moreover, it seems that the sample distribution follows some symmetric theoretical distribution. From the findings of mathematical statistics, it is known that for the correlation coefficient, by converting the sample correlation coefficient using the following formula, it follows a t-distribution with degrees of freedom of <span class="math inline">\(n-2\)</span>.</p>
<p>In the field of psychology, it’s crucial to grasp the basics of statistics, specifically how to conduct a correlation analysis. You may confront this formula while dealing with such analysis:</p>
<p><span class="math display">\[ t = \frac{r\sqrt{n-2}}{\sqrt{1-r^2}} \]</span></p>
<p>This can look a little daunting at first, but don’t worry, let’s break it down. This is the formula to calculate the value of ‘t’. Here, ‘t’ is the t-statistic, ‘r’ is the correlation coefficient, and ‘n’ is the number of data pairs. This t-statistic is commonly used in hypothesis testing, specifically when dealing with Pearson’s correlation. Remember, understanding this foundational statistical formula is vital to grasp more complex psychological analysis and concepts we will explore further. Using R and RStudio makes such statistical analysis more efficient and accessible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">T =</span> R <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">18</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">-</span> R<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> T)) <span class="sc">+</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), <span class="at">binwidth =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 自由度18のt分布の確率密度関数を追加</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dt, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">18</span>), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Y軸のラベルを変更</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter07_files/figure-html/tprob-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We will use this to perform a test of correlation coefficient. Below, assuming a sample correlation coefficient of <span class="math inline">\(r=0.5\)</span> with a sample size of 20, we will explain the procedure step by step.</p>
<ol type="1">
<li>The null hypothesis sets the population correlation, <span class="math inline">\(\rho = 0.0\)</span>. The alternative hypothesis is <span class="math inline">\(\rho \neq 0.0\)</span>.</li>
<li>The test statistic is denoted as ‘t’, which is the transformed correlation coefficient ‘r’.</li>
<li>For our decision criteria, we will set <span class="math inline">\(\alpha = 0.05\)</span>. That is, we want to control the probability of mistakenly rejecting the hypothesis that the population correlation is 0 to be less than 5%.</li>
<li>Calculate the test statistic. From <span class="math inline">\(n=20, r=0.5\)</span>, <span class="math display">\[t = \frac{0.5\times(\sqrt{18})}{\sqrt{1-0.5^2}} = 2.449\]</span></li>
</ol>
<p>This equation is saying that we are calculating the value of t (which is a statistic we often use in psychology) by taking 0.5 times the square root of 18 (which could be any given numbers in your actual data), then dividing this by the square root of 1 minus 0.5 squared. After calculating, you will find that the value of t in this case is 2.449. 5. The probability that the absolute value of the sample correlation coefficient exceeds 0.5 can be calculated from the theoretical values ​​of the t-distribution as follows. Alternatively, the critical value, which is 5% at both ends of the t-distribution, can be calculated in the following way.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">18</span>) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.5</span><span class="sc">^</span><span class="dv">2</span>), <span class="at">df =</span> <span class="dv">18</span>)) <span class="sc">*</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02476956</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> <span class="dv">18</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.100922</code></pre>
</div>
</div>
<p>The important thing to note here is that the purpose of our current test is to determine “whether we can reject the null hypothesis that the population correlation is zero,” with no interest in the sign of the correlation coefficient; we consider it in absolute value terms. The <code>pt</code> function represents the cumulative area up to a certain probability point, so by subtracting it from one, we are showing the probability of obtaining a value higher than this probability point. Because the <span class="math inline">\(t\)</span> distribution is a symmetric distribution, twice this value is the probability of occurrence when considered in absolute terms. If this value is less than 5%, we can judge it to be statistically significant. Based on our results, it is indeed fair to say that our findings are statistically significant.</p>
<p>Furthermore, a minor point to note in expression is that this probability refers to the probability of obtaining more extreme values “than or equal to” this observed value. It does not refer to the probability of obtaining this exact observed value. This is because probabilities are considered as areas, and there’s no area assigned to a single point.</p>
<p>The function <code>qt</code> represents probabilistic points, from which we can determine if the realized value exceeded these points, hence statistically significant. The value calculated from our realized value is <span class="math inline">\(t(18)=2.449\)</span>, and since this is greater than the critical value of <span class="math inline">\(2.100\)</span>, we can conclude that it is significant.</p>
</section>
<section id="probability-of-errors-in-two-types-of-tests" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="probability-of-errors-in-two-types-of-tests"><span class="header-section-number">7.4</span> Probability of Errors in Two Types of Tests</h2>
<p>In any statistical test, there is always a possibility of making wrong conclusions. For instance, when you conduct a hypothesis test, you might incorrectly reject the null hypothesis (an error known as “Type I Error”), or you may incorrectly hold on to the null hypothesis when it’s false (an error referred to as “Type II Error”).</p>
<p>Understanding these two types of errors and being able to control their probabilities is one of the indispensable skills in statistical analysis. This skill aids in producing more precise and reliable research findings. In the next section, we’re going to explore how to do this using R and RStudio. It may be challenging at first, but remember, practice makes perfect.</p>
<p>Although we have carefully examined the calculations above, in practical situations we only have one sample and only one sample statistic is computed. Since this is your own valuable data, it might be difficult to intuitively grasp that it’s just a specific case derived from the sample distribution.</p>
<p>When conducting a correlation coefficient test, use R’s <code>cor.test</code> function as follows. Here, we use the <code>mvrnorm</code> function to create hypothetical data with a correlation coefficient of 0.5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">17</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>sampleData <span class="ot">&lt;-</span> <span class="fu">mvrnorm</span>(n,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sigma =</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">empirical =</span> <span class="cn">TRUE</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sampleData[, <span class="dv">1</span>], sampleData[, <span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  sampleData[, 1] and sampleData[, 2]
t = 2.4495, df = 18, p-value = 0.02477
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.07381057 0.77176071
sample estimates:
cor 
0.5 </code></pre>
</div>
</div>
<p>We can confirm that the values of t, degrees of freedom, and the <span class="math inline">\(p\)</span> value shown in the results correspond with the examples we showed earlier. Moreover, the confidence interval of the correlation coefficient and the sample correlation coefficient itself are also indicated. From the fact that this confidence interval does not cross zero, we can see that the null hypothesis would be rejected.</p>
<p>We already know that if we take a subset of a data set with a correlation of 0, the correlation coefficient won’t necessarily be 0; it might be a number like 0.5. Even if the population correlation is 0, it’s possible that the sample correlation might yield a value close to 0. What this suggests is that we shouldn’t place too much importance on the values derived from the sample (of course, this assumes we are working with generalizations). Furthermore, the null hypothesis is that the “population correlation is 0”. So, even if it gets <strong>rejected</strong>, it merely means that “we can’t claim that the population correlation is 0”. From this, it’s inappropriate to argue that the population correlation is likely around <span class="math inline">\(r=0.5\)</span>, or that the <span class="math inline">\(p\)</span> value being significantly lower than 5% at 2.4% speaks to the importance of the evidence. This query is based on the hypothetical situation of the population correlation being 0. It does not mean that we are examining what the actual degree of population correlation is. This point is easily misunderstood, so take particular care in understanding this detail.</p>
<p>Hopefully, by now, it has become easier to understand Type 1 and Type 2 errors in a more concrete way. Type 1 error is the probability of making a decision using the statistic calculated from the sample correlation, if the null hypothesis is correct. This is exactly what we saw in the previous steps.</p>
<p>Let’s take a look at this from a different angle. <code>cor.test</code> can be used to calculate the confidence interval of a sample statistic. Let’s analyze the proportion that correctly includes $ = 0 $, which is the null hypothesis here, within this confidence interval. The object returned by the <code>cor.test</code> function includes something named <code>conf.int</code>, which by default contains the 95% confidence interval. Before starting the simulation, we created a two-column data frame to store the results. After the simulation, we used the <code>ifelse</code> function to determine whether the population correlation was included.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>iter <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>intervals <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> iter, <span class="at">ncol =</span> <span class="dv">2</span>))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(intervals) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Lower"</span>, <span class="st">"Upper"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>iter) {</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  selected_row <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>N, <span class="dv">20</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  s_i <span class="ot">&lt;-</span> X[selected_row, ]</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  cor_i <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(s_i[, <span class="dv">1</span>], s_i[, <span class="dv">2</span>])</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  intervals[i, ] <span class="ot">&lt;-</span> cor_i<span class="sc">$</span>conf.int[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> intervals <span class="sc">%&gt;%</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">FLG =</span> <span class="fu">ifelse</span>(Lower <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> Upper <span class="sc">&gt;=</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">type1error =</span> <span class="fu">mean</span>(FLG)) <span class="sc">%&gt;%</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  type1error
1       0.95</code></pre>
</div>
</div>
<p>In this instance, correct judgments were made at a rate of 95%. In other words, the rate at which errors occurred was 5%, confirming that the goal of keeping the Type 1 error probability below 5% was successfully achieved.</p>
<p>Similarly, a Type II error is the probability of accepting the null hypothesis when it is not correct. If we were to simulate this, it would go as follows. First, let’s create a situation where the population correlation is not zero. For now, let’s assume that the population correlation is 0.5 and try to plot the population distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">mvrnorm</span>(N,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sigma =</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="at">ncol =</span> <span class="dv">2</span>),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">empirical =</span> <span class="cn">TRUE</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>X <span class="sc">%&gt;%</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> V1, <span class="at">y =</span> V2)) <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter07_files/figure-html/gg0.5-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Let’s now extract a dataset of sample size 20 and proceed to test it. Based on the test result, we’ll create an object that is ‘1’ if it is significant, and ‘0’ if it is not, and then consider the correctness of our decision.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>iter <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>judges <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>iter) {</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  selected_row <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>N, <span class="dv">20</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  s_i <span class="ot">&lt;-</span> X[selected_row, ]</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  cor_i <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(s_i[, <span class="dv">1</span>], s_i[, <span class="dv">2</span>])</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  judges <span class="ot">&lt;-</span> <span class="fu">c</span>(judges, cor_i<span class="sc">$</span>p.value)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">p =</span> samples) <span class="sc">%&gt;%</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">FLG =</span> <span class="fu">ifelse</span>(p <span class="sc">&lt;=</span> <span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">sig =</span> <span class="fu">sum</span>(FLG <span class="sc">==</span> <span class="dv">1</span>),</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">non.sig =</span> <span class="fu">sum</span>(FLG <span class="sc">==</span> <span class="dv">0</span>),</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">type2error =</span> non.sig <span class="sc">/</span> iter</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sig non.sig type2error
1 5790    4210      0.421</code></pre>
</div>
</div>
<p>In this case, the correlation coefficient was 0.5, and the null hypothesis should have been rejected, but 42.1% of the cases were incorrectly deemed not significant. In psychological research, it is desirable to have this probability <span class="math inline">\(\beta\)</span> less than 0.2, or inversely, to have a detection rate of over 0.8. Therefore, it can be said that in this particular instance, there wasn’t sufficient detection power.</p>
<p>Of course, in reality, we do not know what the parent correlation might be. It could be <span class="math inline">\(0.3\)</span>, or it could be <span class="math inline">\(-0.5\)</span>. This means that Type II errors are not within the researcher’s control, and at most, the researcher can strive to collect samples pertaining to variables where a large correlation is anticipated.</p>
<p>The probability of Type 1 and Type 2 errors is a function of the sample size and effect size (in this case, the scale of the population correlation). As researchers can determine the sample size, they should form an estimate of the effect, decide on the standard for the error probability they want to control, and then reasonably determine the sample size.</p>
</section>
<section id="practice-problems-an-example-of-correlation-test" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="practice-problems-an-example-of-correlation-test"><span class="header-section-number">7.5</span> Practice Problems: An Example of Correlation Test</h2>
<ol type="1">
<li>Let’s try to approximate the sampling distribution, through the use of a histogram of random numbers, when we observe the sample correlation from a population with a correlation coefficient of 0, by taking a sample with a size of 10.</li>
<li>Similarly, let’s try to approximate the sampling distribution when observing the sample correlation of a sample size of 50, using a histogram of random numbers. How does this differ when compared to sample sizes of 20 or 10?</li>
<li>Can we say that a sample correlation of <span class="math inline">\(r=-0.3\)</span> is statistically significant with a sample size of 50? Use <code>cor.test</code> to validate, and describe the testing outcomes and your decisions.</li>
<li>Let’s suppose the sample correlation is <span class="math inline">\(r=-0.3\)</span>. Would it be statistically significant if the sample sizes were 10, 20, 50, and 1000, respectively? Perform a test using <code>cor.test</code>, and summarize the results. What can we interpret from these findings?</li>
<li>Suppose the population correlation is <span class="math inline">\(\rho = -0.3\)</span>. How much statistical power can we expect when the sample size is 20? Please approximate this using simulation.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Ikeda2016" class="csl-entry" role="listitem">
池田功毅, and 平石界. 2016. <span>“心理学における再現可能性危機：問題の構造と解決策.”</span> <em>心理学評論</em> 59 (1): 3–14. <a href="https://doi.org/10.24602/sjpr.59.1_3">https://doi.org/10.24602/sjpr.59.1_3</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>You can streamline this process by iteratively generating random numbers of sample size 20 from <code>mvrnorm</code>. To have a concrete image of the population, we chose the method of repeatedly sampling from a population with a parent correlation of <code>0</code>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter06.html" class="pagination-link" aria-label="Probability and Simulation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability and Simulation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter08.html" class="pagination-link" aria-label="Testing for Difference in Means">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Testing for Difference in Means</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>