<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Psychological Statistics - 6&nbsp; Probability and Simulation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter07.html" rel="next">
<link href="./chapter05.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter06.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability and Simulation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Psychological Statistics</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Introduction-to-Psychological-Statistics.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Introduction-to-Psychological-Statistics.epub">
              <i class="bi bi-bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Let’s Start with R/RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentals of R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Handling with R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Creating Reports with R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Programming with R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter06.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability and Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The Logic and Errors of Statistical Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Testing of Mean Difference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Test of the Difference in Mean Values of Multiple Groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simulation of Null Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Basics of Regression Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Expanding Linear Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduction to Multivariate Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#understanding-and-application-of-probability" id="toc-understanding-and-application-of-probability" class="nav-link active" data-scroll-target="#understanding-and-application-of-probability"><span class="header-section-number">6.1</span> Understanding and Application of Probability</a></li>
  <li><a href="#probability-distribution-functions" id="toc-probability-distribution-functions" class="nav-link" data-scroll-target="#probability-distribution-functions"><span class="header-section-number">6.2</span> Probability Distribution Functions</a></li>
  <li><a href="#random-numbers" id="toc-random-numbers" class="nav-link" data-scroll-target="#random-numbers"><span class="header-section-number">6.3</span> Random Numbers</a>
  <ul class="collapse">
  <li><a href="#how-to-use-random-numbers" id="toc-how-to-use-random-numbers" class="nav-link" data-scroll-target="#how-to-use-random-numbers"><span class="header-section-number">6.3.1</span> How to Use Random Numbers</a></li>
  </ul></li>
  <li><a href="#exercise-using-random-numbers" id="toc-exercise-using-random-numbers" class="nav-link" data-scroll-target="#exercise-using-random-numbers"><span class="header-section-number">6.4</span> Exercise: Using Random Numbers</a></li>
  <li><a href="#population-and-sample" id="toc-population-and-sample" class="nav-link" data-scroll-target="#population-and-sample"><span class="header-section-number">6.5</span> Population and Sample</a></li>
  <li><a href="#consistency" id="toc-consistency" class="nav-link" data-scroll-target="#consistency"><span class="header-section-number">6.6</span> Consistency</a></li>
  <li><a href="#unbiasedness" id="toc-unbiasedness" class="nav-link" data-scroll-target="#unbiasedness"><span class="header-section-number">6.7</span> Unbiasedness</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">6.8</span> Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#confidence-interval-in-cases-where-the-population-variance-of-the-normal-distribution-is-known" id="toc-confidence-interval-in-cases-where-the-population-variance-of-the-normal-distribution-is-known" class="nav-link" data-scroll-target="#confidence-interval-in-cases-where-the-population-variance-of-the-normal-distribution-is-known"><span class="header-section-number">6.8.1</span> Confidence Interval in Cases Where the Population Variance of the Normal Distribution is Known</a></li>
  <li><a href="#confidence-interval-when-the-population-variance-of-the-normal-distribution-is-unknown" id="toc-confidence-interval-when-the-population-variance-of-the-normal-distribution-is-unknown" class="nav-link" data-scroll-target="#confidence-interval-when-the-population-variance-of-the-normal-distribution-is-unknown"><span class="header-section-number">6.8.2</span> Confidence Interval When the Population Variance of the Normal Distribution is Unknown</a></li>
  </ul></li>
  <li><a href="#practice-problems-estimators-and-interval-estimation" id="toc-practice-problems-estimators-and-interval-estimation" class="nav-link" data-scroll-target="#practice-problems-estimators-and-interval-estimation"><span class="header-section-number">6.9</span> Practice Problems: Estimators and Interval Estimation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Probability and Simulation</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="understanding-and-application-of-probability" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="understanding-and-application-of-probability"><span class="header-section-number">6.1</span> Understanding and Application of Probability</h2>
<p>In our daily life, we often use the term “probability”. For instance, when talking about the possibility of rain tomorrow, we might use probabilities like “60% chance of rain”. However, what exactly does this “60%” mean? And how is probability used in the context of statistics?</p>
<p>Probability is a measure of how likely something is to happen. In the case of “60% chance of rain”, it means that based on current weather data, in 60 out of 100 cases, it would rain the following day. This does not guarantee that it will rain tomorrow in reality, but rather highlights the likelihood based on existing information.</p>
<p>In the world of statistics, probability is extremely useful. It not only allows us to predict future events based on past data, but also helps us measure the reliability of these predictions.</p>
<p>In the following sections, we will look at how to calculate probability and use it in statistical analysis with R and RStudio.</p>
<p>Statistics and probability have a close relationship. To begin with, collecting a lot of data allows us to see overall trends that are not visible in individual cases. This is where the concept of probability comes into play to express these trends. Next, even when there isn’t much data, when it’s considered a sample extracted from a larger whole, we consider how the sample reflects the characteristics of the whole. Here, when expressing the randomness of extracting a part from the overall trend, we will use the concept of probability. Finally, even for mechanisms whose behavior is theoretically and fundamentally understood, systematic deviations or occassional errors that could only be considered accidental may occur in real and practical situations. The former can be addressed by adjusting the mechanism, but the latter requires considering the probability that these accidents will occur.</p>
<p>Psychology conducts research on humans, but it’s not possible to study every individual at once. Therefore, we take samples and conduct surveys or experiments (case 2). In data science, we often deal with large datasets containing tens of thousands of records. However, in psychology, it is common to only have a few or several dozen cases. Additionally, even if we can theorize and model psychological tendencies, there is a high possibility that actual behavior will contain errors (case 3). With this in mind, the data obtained in psychology can be considered as random variables, and it is used together with <strong>inferential statistics</strong> to estimate the characteristics of a population from a small sample.</p>
<p>In strict mathematical terms, <strong>probability</strong> is defined as the accumulation of precise concepts such as sets, integrals, and measures<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Here, rather than delving into these details, I would like you to simply understand it as “a way of expressing the likelihood of a particular outcome occurring, with a real number anywhere between 0 and 1”. From this definition, it is possible to interpret probability as “the proportion of successful outcomes out of all possible combinations”, and also as “the degree of belief related to the strength of perceived truths, weighted by one’s subjectivity.”[^6.2] You may have thought that the probability we’ve been learning so far is a dull concept - simply listing all permutations and combinations. However, it’s actually a very relatable and versatile concept, because we can treat numbers such as “eight or nine times out of ten, it’s right” (meaning we consider it about 80-90% likely) as a type of probability. As one of the key points to facilitate your understanding, it might be helpful to think of probability as an area. The concept of probability expresses what proportion of the total space of possible situations is occupied by the occurrence of an event. In other words, thinking of probability as how much of an area within all possible scenarios an event takes up (<span class="citation" data-cites="Hiraoka200910">平岡 and 堀 (<a href="#ref-Hiraoka200910" role="doc-biblioref">2009</a>)</span> consistently explains this in his book. This way of explanation makes it easier to understand concepts like conditional probability).</p>
<p>[^6.2] The former interpretation involves the probability we learn until high school, often referred to as frequency-based probability. On the other hand, the latter interpretation, as seen in daily usage like a precipitation probability of X%, is sometimes called subjective probability. While there are critics who argue these differences in interpretation are due to ideological disputes rather than mathematical reasons, in reality, Kolmogorov’s axioms are arranged to hold from either perspective. Personally, I believe that either is fine as long as users find it easy to understand and calculate.</p>
<p>However, it’s vital that we distinguish between a ‘random variable’ and its ‘realized value’. The values contained in a dataset or spreadsheet are indeed the <strong>realized values of a random variable</strong>, not the random variable itself. The term <strong>random variable</strong> refers to a variable in its uncertain state. A die is a random variable, and the number it lands on is a realized value of that random variable. Similarly, a psychological variable is a random variable, and any data we collect are its realized values. We come to understand the characteristics of a variable through its realized values and then use this understanding to infer the overall picture.</p>
<p>You may find it challenging to advance debates using abstract entities beyond the data right in front of you. In fact, everyone feels this way because understanding probability accurately is very difficult. However, through the functions implemented in computer languages like R, let’s gradually understand it more concretely and tactically by operating on it.</p>
</section>
<section id="probability-distribution-functions" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="probability-distribution-functions"><span class="header-section-number">6.2</span> Probability Distribution Functions</h2>
<p>The realization values of a random variable follow a <strong>probability distribution</strong>. A probability distribution is an overview that shows exactly how likely each realization value is expected to occur. Typically, it is represented by a function. The names for these distributions vary depending on whether the realization values are continuous or discrete. A continuous probability distribution function is referred to as a <strong>Probability Density Function (PDF)</strong>, while a discrete probability distribution function is referred to as a <strong>Probability Mass Function (PMF)</strong>.</p>
<p>In R, several functions related to probability are prepared from the onset. For the <strong>normal distribution</strong>, which is the most well-known probability distribution, we have the following functions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 標準のプロット関数，curve</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x), <span class="at">from =</span> <span class="sc">-</span><span class="dv">4</span>, <span class="at">to =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter06_files/figure-html/normal-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot2を使ってカッコよく</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.3     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">by =</span> <span class="fl">0.01</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">dnorm</span>(x)) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter06_files/figure-html/normlByggplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here, we use a function called <code>dnorm</code>. The <code>d</code> stands for Density (probability density), and <code>norm</code> is part of Normal Distribution. In R, we create a function by naming the probability distribution (here, <code>norm</code>) and adding a prefix letter (<code>d</code>). Other prefix letters such as <code>p</code>, <code>q</code>, and <code>r</code> exist. They are used in functions like <code>dpois</code> (density function of the Poisson distribution), <code>pnorm</code> (cumulative distribution function of the normal distribution), and <code>rbinom</code> (random number generation from the binomial distribution).</p>
<p>Let’s continue with the explanation using the normal distribution as an example. The shape of the normal distribution is characterized by the mean <span class="math inline">\(\mu\)</span> and the standard deviation <span class="math inline">\(\sigma\)</span>. These numbers that describe the characteristics of probability distributions are referred to as <strong>parameters</strong>. For example, the following three curves represent normal distributions with different parameters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">by =</span> <span class="fl">0.01</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">y1 =</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">y2 =</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">1</span>, <span class="at">sd =</span> <span class="fl">0.5</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y3 =</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">sd =</span> <span class="dv">2</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>x) <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> value, <span class="at">color =</span> name)) <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter06_files/figure-html/normals-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The mean is also called the location parameter, while the standard deviation is referred to as the scale parameter. These parameters affect the position and spread of the distribution. In other words, you can determine the parameters of a normal distribution to best fit the data. If the distribution has the features of being symmetrical and unimodal, then a wide variety of patterns can be represented by a normal distribution.</p>
<p>Now, the functions we used in the above examples all start with ‘d’ in ‘dnorm’, representing the height of the probability distribution density. So, what do ‘p’ and ‘q’ represent? I will provide examples of numbers and figures so you can confirm their correlations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 累積分布関数</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.96</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9750021</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 累積分布の逆関数</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<p>If numbers are not intuitively understandable, let’s take a look at the following figure. The <code>pnorm</code> function returns the area (or the probability, represented as the colored region in the code below) up to a given x-coordinate value. The <code>qnorm</code> function, on the other hand, takes a probability (equal to an area), integrates the region under the probability density function curve, and returns the x-coordinate value at which this integration yields that probability.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 描画</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fl">0.9</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="do">## 全体の正規分布カーブ</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">by =</span> <span class="fl">0.01</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="do">## qnorm(0.975)までのデータ</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="sc">-</span><span class="dv">4</span>, <span class="fu">qnorm</span>(prob), <span class="at">by =</span> <span class="fl">0.01</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="do">## データセットの違いに注意</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> df1, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> df2, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> y), <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="do">## 以下装飾</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">qnorm</span>(prob), <span class="at">y =</span> <span class="fu">dnorm</span>(<span class="fu">qnorm</span>(prob)), <span class="at">xend =</span> <span class="fu">qnorm</span>(prob), <span class="at">yend =</span> <span class="dv">0</span>),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.2</span>, <span class="st">"cm"</span>)), <span class="at">color =</span> <span class="st">"red"</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter06_files/figure-html/p_qNorm2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The leading characters such as <code>d</code>, <code>p</code>, <code>q</code>, <code>r</code> are also attached to other probability distribution functions. Let’s now explain about <code>r</code>.</p>
</section>
<section id="random-numbers" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="random-numbers"><span class="header-section-number">6.3</span> Random Numbers</h2>
<p>Explaining what a random number is can be as difficult as describing “what does it mean to be random (or a probabilistic variable).” Put simply, this refers to a series of numbers with no apparent pattern. However, since computers calculate numbers accurately according to algorithms, strictly speaking, they cannot generate random, rule-less numbers. The numbers generated by computers, which appear to be random, are actually produced according to a random number generation algorithm, and hence bear a certain regularity. Therefore, they are more accurately referred to as “pseudo-random numbers”.</p>
<p>However, it is significantly more effective in generating sequences without any rules, compared to humans randomly naming numbers<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Even though it is a pseudo process, it serves its purpose quite well. For example, when you “pull a gacha” in an app, the system generates a numerical value using a random number internally and makes a judgement on hit-miss based on this number. In other scenarios, like in RPG games, there is a fixed probability that an attack will fail or score a “critical hit.” The crucial point here is that even if these games are programmed based on unpredictable numbers, we still want to have a certain degree of control over the statistical properties, namely the probability of occurrence of realized values.</p>
<p>So, there comes a point when you might want to generate random numbers based on a particular probability distribution. Fortunately, by transforming uniform random numbers (where all possible values occur with equal probability) through a function, you can create random numbers that follow a range of probability distributions such as the normal distribution. In R, several functions are implemented that generate random numbers according to various probability distributions. For example, the following code generates 10 random numbers following the normal distribution with a mean of 50 and a standard deviation of 10.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 49.48839 47.09282 53.02918 35.94514 46.78571 33.21525 38.31609 57.35023
 [9] 50.33838 58.76588</code></pre>
</div>
</div>
<p>For example, if you are trying to create practice problems for psychological statistics and you need a suitable number sequence, this method might work well for you. However, if you try to create the same problem again, since it’s a random number, a different number might come out.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 50.25454 42.58257 46.29270 53.46542 45.95964 56.89460 47.79396 64.62661
 [9] 49.98286 41.97500</code></pre>
</div>
</div>
<p>You might want to generate random numbers with reproducibility, given they are merely pseudorandom numbers. In such a case, use the <code>set.seed</code> function. Since pseudorandom numbers are calculated from the seed of the internal random number generator, fixing this number will enable the same random numbers to be reproduced.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># seedを指定</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.5855288  0.7094660 -0.1093033</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 同じseedを再設定</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  0.5855288  0.7094660 -0.1093033</code></pre>
</div>
</div>
<section id="how-to-use-random-numbers" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="how-to-use-random-numbers"><span class="header-section-number">6.3.1</span> How to Use Random Numbers</h3>
<p>One application of random numbers, as we previously mentioned, would be when we want to program behaviors that appear to be the result of chance.</p>
<p>In fact, there are other uses as well. One is when you want to know a probability distribution in specific terms. What follows are histograms for when we choose <span class="math inline">\(n = 10,100,1000,10000\)</span> from the standard normal distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>rN10 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>rN100 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>rN1000 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>rN10000 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">N =</span> <span class="fu">c</span>(</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">10</span>), <span class="fu">rep</span>(<span class="dv">2</span>, <span class="dv">100</span>),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rep</span>(<span class="dv">3</span>, <span class="dv">1000</span>), <span class="fu">rep</span>(<span class="dv">4</span>, <span class="dv">10000</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">X =</span> <span class="fu">c</span>(rN10, rN100, rN1000, rN10000)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">N =</span> <span class="fu">as.factor</span>(N)) <span class="sc">%&gt;%</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> X, <span class="at">fill =</span> N)) <span class="sc">+</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 縦軸を相対頻度に</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..)) <span class="sc">+</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>N)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter06_files/figure-html/rnorm-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looking at this, the first ten or so histograms appear to have irregular distributions. However, as the number increases to 100,1000 and beyond, we can see that they gradually approximate the theoretical shape of a normal distribution.</p>
<p>R incorporates probability distribution functions, including well-known statistical distributions such as the Poisson, binomial, t-distribution, F-distribution, and Chi-square (<span class="math inline">\(\chi^2\)</span>) distribution. It might be hard to visualize these distributions just by hearing the values of their parameters. In such cases, you can generate a large number of random numbers with specified parameters and create a histogram. This enables you to visually comprehend the shape of the probability distribution function, leading to a more concrete understanding.</p>
<p>Indeed, one reason why Bayesian statistics are flourishing recently is largely due to the contributions of computer science. The random number generation technique, known as <strong>Markov Chain Monte Carlo method</strong> (MCMC method), allows us to create random numbers even from posterior distributions produced by models that do not have explicit names. Although it is difficult to demonstrate this distribution analytically, by generating random numbers from it and viewing its histogram, you can visualize its shape.</p>
<p>Additionally, the advantages of this random usage method are not just limited to visualization. Suppose you want to know the area (=probability) within a certain range in the standard normal distribution. For example, let’s try to find the area within the range from the probability point -1.5 to +1.5. Since we know the formula for the normal distribution, we can find this area by following the steps below. <span class="math display">\[ p = \int_{-1.5}^{+1.5} \frac{1}{\sqrt{2\pi}}e^{-\frac{x^2}{2}} dx \]</span></p>
<p>This mathematical equation is an integral that represents the probability density function of a standard normal distribution in the range of -1.5 to +1.5. Simply put, it helps us calculate the probability that a random variable falls within this defined range. Remember, a normal distribution, often called the “bell curve,” is a common pattern for statistical data in psychology, and many other fields of study. Understanding this concept and being able to use R to compute these probabilities will be an invaluable tool in your statistical analysis toolbox.</p>
<p>Naturally, knowing the <code>pnorm</code> function allows us to obtain numerical solutions, as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="sc">+</span><span class="fl">1.5</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="sc">-</span><span class="fl">1.5</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8663856</code></pre>
</div>
</div>
<p>We can obtain an approximate solution by using random numbers, as demonstrated below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100000</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">X =</span> x) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 該当する範囲かどうかを判定する変数を作る</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">FLG =</span> <span class="fu">ifelse</span>(X <span class="sc">&gt;</span> <span class="sc">-</span><span class="fl">1.5</span> <span class="sc">&amp;</span> X <span class="sc">&lt;</span> <span class="fl">1.5</span>, <span class="dv">1</span>, <span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">FLG =</span> <span class="fu">factor</span>(FLG, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"in"</span>, <span class="st">"out"</span>)))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="do">## 計算</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(FLG) <span class="sc">%&gt;%</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prob =</span> n <span class="sc">/</span> <span class="dv">100000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  FLG       n  prob
  &lt;fct&gt; &lt;int&gt; &lt;dbl&gt;
1 in    86642 0.866
2 out   13358 0.134</code></pre>
</div>
</div>
<p>Here, we have generated 10,000 random numbers and created a factor-type variable, <code>FLG</code>, which indicates whether these numbers fall within a specified range (assigning a 1 if they do, and a 2 if not). We group and count the number according to this variable and divide by the total to get the relative frequency. Probability represents the proportion of a certain area within the whole. In this case, we obtained a figure of <code>0.866</code> for the specified range, which is nearly identical to the solution calculated by the <code>pnorm</code> function.</p>
<p>Furthermore, it is easy to visualize the range with the following steps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">## 可視化</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> X, <span class="at">fill =</span> FLG)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter06_files/figure-html/norm_vis-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s reiterate, even if you have trouble visualizing the shape of a probability distribution, or find it difficult to represent its formula analytically, you can still visualize it as a histogram using specific numbers, and approximate probability calculations.</p>
<p>Remember, these are only approximations, so if you don’t trust their accuracy, you can easily increase the number of random numbers generated by ten or a hundred times. Given the computational capabilities of modern computers, such an increase will not significantly burden the computational costs. The fact that complex integral calculations become a matter of descriptive statistics (counting) is a significant advantage in terms of concrete understanding.</p>
<p>I would like you to think a bit further. Psychologists gather data through psychological experiments and surveys. However, considering individual differences and errors, these data are considered to be random variables. Even with a few to several dozen pieces of data in front of you, it is assumed to follow a normal distribution, and statistical processing is carried out. This is essentially the same as what is done for data generated by random numbers. In other words, it is possible to simulate using random numbers before conducting a survey experiment. Before going all-in with the real survey or experiment, it is crucial to concretely confirm what characteristics the data you are about to collect could have.</p>
</section>
</section>
<section id="exercise-using-random-numbers" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="exercise-using-random-numbers"><span class="header-section-number">6.4</span> Exercise: Using Random Numbers</h2>
<p>Let’s try approximating the following values using normal random numbers. Be sure to devise a method that allows you to obtain accuracy to the second decimal place, comparing these approximations to the ‘true’ values obtained through analytical computations and settings.</p>
<ol type="1">
<li>The expected value of a normal distribution with a mean of 100, and a standard deviation of 8. Note, the expected value of a continuous random variable is represented by the following formula: <span class="math display">\[E[X] = \int_{-\infty}^{\infty} x f(x) \, dx\]</span> Here, <span class="math inline">\(x\)</span> represents the random variable, and <span class="math inline">\(f(x)\)</span> is the probability density function, which is obtained by integrating over the entire domain of the probability density function. The expected value of a normal distribution coincides with the mean parameter, so the true value in this case is the pre-set <span class="math inline">\(100\)</span>.</li>
<li>Let’s try calculating the variance of a normal distribution with a mean of 100 and a standard deviation of 3. Note that the variance of a continuous random variable is expressed by the following equation: <span class="math display">\[\sigma^2 = \int_{-\infty}^{\infty} (x - \mu)^2 f(x) \, dx\]</span> Here, <span class="math inline">\(\mu\)</span> is the expected value of the random variable, and for a normal distribution, the variance aligns with the square of the standard deviation parameter. Therefore, in this case, the true value is <span class="math inline">\(3^2 = 9\)</span>.</li>
<li>The area of the probability variable <span class="math inline">\(X\)</span>, which follows a normal distribution with an average of 65 and a standard deviation of 10, where <span class="math inline">\(90 &lt; X &lt; 110\)</span>. The results of analytical calculations are as follows.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">108</span>, <span class="at">mean =</span> <span class="dv">65</span>, <span class="at">sd =</span> <span class="dv">10</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">92</span>, <span class="at">mean =</span> <span class="dv">65</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003458434</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>The probability of realizing a value of 7 or above in a normal distribution with a mean of 10 and a standard deviation of 10. The results calculated analytically are as follows.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">7</span>, <span class="at">mean =</span> <span class="dv">10</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6179114</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Let’s assume we have two random variables, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. <span class="math inline">\(X\)</span> follows a normal distribution with a mean of 10 and a standard deviation (SD) of 10, while <span class="math inline">\(Y\)</span> follows a normal distribution with a mean of 5 and an SD of 8. Given that <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent, please use random numbers to verify that the mean and variance of their sum, <span class="math inline">\(Z=X+Y\)</span>, are equal to the sum of the original means and variances of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
</ol>
</section>
<section id="population-and-sample" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="population-and-sample"><span class="header-section-number">6.5</span> Population and Sample</h2>
<p>Until now, we have looked at how to use random numbers to explore the properties of probability distributions. From here on, we are going to consider how probability distributions are used in inferential statistics. In inferential statistics, the whole group we want to know about is called the <strong>population</strong>, and the subset of data obtained from it is referred to as a <strong>sample</strong>. Inferential statistics or statistical inference entails using sample statistics to infer the properties of the population. The statistical measures that represent the characteristics of the population are called <strong>parameters</strong>, indicating information about the population with terms such as population mean and population variance, which are prefaced with the word “population”. Similarly, the mean and variance of a sample can be calculated, and in these cases, terms such as sample mean and sample variance are used to explicitly emphasize the difference.</p>
<p>Let’s use a specific example involving random numbers. Suppose we have a village made up of 100 people. We decide to measure the heights of these villagers and collect data. Thinking of 100 appropriate random numbers can be tedious, so we’ll make replacements by generating random numbers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 100人分の身長データをつくる。小数点以下2桁を丸めた</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>Po <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">150</span>, <span class="at">sd =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">2</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Po)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 155.86 157.09 148.91 145.47 156.06 131.82 156.30 147.24 147.16 140.81
 [11] 148.84 168.17 153.71 155.20 142.49 158.17 141.14 146.68 161.21 152.99
 [21] 157.80 164.56 143.56 134.47 134.02 168.05 145.18 156.20 156.12 148.38
 [31] 158.12 171.97 170.49 166.32 152.54 154.91 146.76 133.38 167.68 150.26
 [41] 161.29 126.20 139.40 159.37 158.54 164.61 135.87 155.67 155.83 136.93
 [51] 144.60 169.48 150.54 153.52 143.29 152.78 156.91 158.24 171.45 126.53
 [61] 151.50 136.57 155.53 165.90 144.13 131.68 158.88 165.93 155.17 137.04
 [71] 150.55 142.15 139.51 173.31 164.03 159.43 158.26 141.88 154.76 160.21
 [81] 156.45 160.43 146.96 174.77 159.71 168.67 156.72 146.92 155.37 158.25
 [91] 140.36 141.45 168.87 146.08 140.19 156.87 144.95 171.58 144.00 143.05</code></pre>
</div>
</div>
<p>Since this village of 100 people is our population, we can calculate the population mean and population variance in the following way.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">mean</span>(Po)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>V <span class="ot">&lt;-</span> <span class="fu">mean</span>((Po <span class="sc">-</span> M)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 母平均</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(M)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 152.4521</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 母分散</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(V)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 123.0206</code></pre>
</div>
</div>
<p>Let’s assume that we have obtained a sample of 10 people randomly from this village. We could select the first 10 people from the vector, but R provides us with a sampling function called <code>sample</code> that we would like to utilize.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>s1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(Po, <span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>s1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 164.61 155.86 136.93 143.29 160.43 168.87 151.50 155.17 153.71 135.87</code></pre>
</div>
</div>
<p>The <code>s1</code> here is our given data. Obtaining data from psychological experiments is like extracting just a small part from the whole. The mean and variance of this sample are called the sample mean and sample variance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(s1)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">&lt;-</span> <span class="fu">mean</span>((s1 <span class="sc">-</span> <span class="fu">mean</span>(s1))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 標本平均</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 152.624</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 標本分散</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(v1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 110.2049</code></pre>
</div>
</div>
<p>In this case, the population mean is 152.4521, and the sample mean is 152.624. Since the only values we actually know are those of the sample, it’s not unreasonable to guess that when we get the sample mean 152.624, the population mean would also be close to 152.624. However, the sample mean varies depending on how the sample is collected. For the sake of illustration, let’s suppose we’ve gathered another sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>s2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(Po, <span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>s2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 154.76 135.87 143.05 171.45 136.57 170.49 156.87 158.25 155.17 155.20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(s2)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>v2 <span class="ot">&lt;-</span> <span class="fu">mean</span>((s2 <span class="sc">-</span> <span class="fu">mean</span>(s2))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 標本平均その2</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 153.768</code></pre>
</div>
</div>
<p>The sample mean obtained this time was 153.768. Upon obtaining this data, surely you would guess that the population mean is likely “close to 153.768”. Comparing sample 1’s 152.624 with sample 2’s 153.768, the former is closer to the correct value of 152.4521 (the differences are -0.1719 and -1.3159 respectively). What this implies is the existence of hit-or-miss scenarios depending on how the sample is selected. Therefore, even when collecting and studying data, whether the result supports the hypothesis or not lies beneath these probabilistic fluctuations.</p>
<p>In other words, a <strong>sample is a random variable, and the sample statistic can also change probabilistically</strong>. When estimating parameters using sample statistics, it is necessary to be familiar with the properties of the sample statistics and the probability distribution they follow. In the following, we will look at desirable properties of estimators which have desirable properties for parameter estimation.</p>
</section>
<section id="consistency" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="consistency"><span class="header-section-number">6.6</span> Consistency</h2>
<p>In the simplest terms, the closer the sample statistic is to the parameter, the better - we would be pleased if they could match. In the previous example, we only drew 10 people from a village of 100, but as the sample size increases to 20, 30, and so on, it can be expected to get closer to the parameter. This property is called <strong>consistency</strong>. It’s one of the characteristics that we want an estimator to have. Fortunately, the sample mean is consistent with the population mean.</p>
<p>Let’s try to confirm this. We could calculate this by varying the sample size. As an example, let’s increase the sample size from 2 to 1000 in a normal distribution with an average of 50 and SD of 10. We’ll consider the process of drawing samples as generating random numbers and calculating their average.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">2</span>, <span class="at">to =</span> <span class="dv">1000</span>, <span class="at">by =</span> <span class="dv">10</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 平均値を格納するオブジェクトを初期化</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(sample_size))</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 反復</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(sample_size)) {</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  sample_mean[i] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(sample_size[i], <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>()</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 可視化</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">size =</span> sample_size, <span class="at">M =</span> sample_mean) <span class="sc">%&gt;%</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> size, <span class="at">y =</span> M)) <span class="sc">+</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">50</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter06_files/figure-html/consistency-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can see, as the sample size increases, it approaches the true value of 50. Let’s change things like the shape of the population distribution, parameters, and sample size to confirm this.</p>
</section>
<section id="unbiasedness" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="unbiasedness"><span class="header-section-number">6.7</span> Unbiasedness</h2>
<p>Estimators are random variables, and their properties can be described using a probability distribution. The probability distribution that a sample statistic follows is called a <strong>sampling distribution</strong>. If the probability density function of the sample distribution is known, it is possible to calculate its expected value or variance. It is also one of the desirable properties of the estimator that the expected value (mean) matches the parameter. This property is referred to as <strong>unbiasedness</strong>.</p>
<p>One of the steps that frustrates beginners in learning psychological statistics is the operation of dividing by <span class="math inline">\(n-1\)</span>, not the sample size <span class="math inline">\(n\)</span>, when calculating the variance. This method is called unbiased variance, which differs from the sample variance. The former has a property of unbiasedness, while the latter does not. Let’s verify this using random numbers.</p>
<p>We continuously draw samples of size <span class="math inline">\(n=20\)</span> from a population with a mean of 50 and a standard deviation (SD) of 10 (the population variance is <span class="math inline">\(10^2=100\)</span>). This is performed by generating random numbers of size 20. Let’s calculate the sample variance and unbiased variance for each sample, and then compute their averages (the expected values of the sample statistics).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>iter <span class="ot">&lt;-</span> <span class="dv">5000</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, iter)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>unbiased_vars <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, iter)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="do">## 乱数の生成と計算</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>iter) {</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  sample <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">20</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  vars[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>((sample <span class="sc">-</span> <span class="fu">mean</span>(sample))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  unbiased_vars[i] <span class="ot">&lt;-</span> <span class="fu">var</span>(sample)</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="do">## 期待値</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 95.08531</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(unbiased_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100.0898</code></pre>
</div>
</div>
<p>The mean, or expected value, of the object <code>vars</code>, which is the calculated sample variance, is 95.0853144 and it deviates somewhat from the established value (true value) of 100. In contrast, the average or expected value of the unbiased variance using <code>var</code>, an embedded function in R, is 100.0898047, and it can be understood that this latter calculation is more preferable as an estimate of the population variance. It is known that sample variance can create bias, and the original formula was modified in advance to correct for this bias. It is hoped that with this explanation, any frustrations will be alleviated.</p>
<p>There’s also the desired property of ‘efficacy’ for estimators, but for more details, please refer to <span class="citation" data-cites="kosugi2023">小杉, 紀ノ定, and 清水 (<a href="#ref-kosugi2023" role="doc-biblioref">2023</a>)</span>. This book includes examples other than the normal distribution, such as sample statistics like correlation coefficients. All are understood through approximation using random number generation. If you’re tired of mathematical-statistical explanations, I highly recommend using this as a reference.</p>
</section>
<section id="confidence-intervals" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="confidence-intervals"><span class="header-section-number">6.8</span> Confidence Intervals</h2>
<p>Sample statistics are a type of probability variable that varies each time a sample is taken. This occurs due to the probabilistic fluctuations introduced when sampling. While the sample mean does possess desirable properties such as consistency and unbiasedness, it does not equate to the population mean.</p>
<p>Using just one realization of a random variable called sample mean to estimate the population mean is pretty much a certain miss in guessing the population mean. Therefore, let’s consider estimating the parameter with a certain range.</p>
<p>For instance, let’s assume a standard normal distribution with a mean of 50 and a standard deviation of 10 as the population distribution. Let’s take a sample size of 10 and use its sample mean as an estimate for the population mean (point estimation). At the same time, give this estimate a bit of width—for example, perform an <strong>interval estimation</strong> of the sample mean <span class="math inline">\(\pm 5\)</span>. With this in mind, let’s check the probability of correctly estimating the true value <span class="math inline">\(0\)</span> using a simulation of repeatedly generated random numbers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>iter <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>SD <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 平均値を格納しておくオブジェクト</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,iter)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>iter) {</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># サンプリングし，標本統計量を保存</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>  sample <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu, <span class="at">sd =</span> SD)</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>  m[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample)</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>result.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">m =</span> m) <span class="sc">%&gt;%</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 推定が一致するとTRUE,外れるとFALSEになる変数を作る</span></span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">point_estimation =</span> <span class="fu">ifelse</span>(m <span class="sc">==</span> mu, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>),</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">interval_estimation =</span> <span class="fu">ifelse</span>(m <span class="sc">-</span> <span class="dv">5</span> <span class="sc">&lt;=</span> mu <span class="sc">&amp;</span> mu <span class="sc">&lt;=</span> m <span class="sc">+</span> <span class="dv">5</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">n1 =</span> <span class="fu">sum</span>(point_estimation),</span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">n2 =</span> <span class="fu">sum</span>(interval_estimation),</span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob1 =</span> <span class="fu">mean</span>(point_estimation),</span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob2 =</span> <span class="fu">mean</span>(interval_estimation)</span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n1   n2 prob1 prob2
1  0 8880     0 0.888</code></pre>
</div>
</div>
<p>As can be seen from the results, the point estimate has never accurately hit the population parameter. This is to be expected, as working with real numbers inevitably leads to discrepancies at some decimal place, and if precision is ignored, there can’t be an exact match. In contrast, when making a prediction with a range, the true value is included within the interval in 8880 out of 10^{4} attempts, and the accuracy rate is 88.8%.</p>
<p>In interval estimation, in order to ensure a 100% correct rate, the interval must be infinitely wide (in the case of estimated population mean). This is virtually equivalent to not making any estimate, so there is a convention to accept about 5% failure and attempt interval estimation with a 95% correct rate. This interval is known as the 95% <strong>confidence interval</strong>.</p>
<section id="confidence-interval-in-cases-where-the-population-variance-of-the-normal-distribution-is-known" class="level3" data-number="6.8.1">
<h3 data-number="6.8.1" class="anchored" data-anchor-id="confidence-interval-in-cases-where-the-population-variance-of-the-normal-distribution-is-known"><span class="header-section-number">6.8.1</span> Confidence Interval in Cases Where the Population Variance of the Normal Distribution is Known</h3>
<p>The simulation above could be applied to adjust the interval until the probability of interval estimation becomes 95%, but indeed, that would be tiresome. Therefore, let’s introduce the properties that have been clarified by inferential statistics.</p>
<p>If it is known that the population follows a normal distribution, with a population mean of <span class="math inline">\(\mu\)</span> and a population variance of <span class="math inline">\(\sigma^2\)</span>, it is understood that the distribution followed by the sample mean is a normal distribution with a mean of <span class="math inline">\(\mu\)</span> and variance of <span class="math inline">\(\frac{\sigma^2}{n}\)</span> (standard deviation of <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>).</p>
<p>The 95% interval for the standard normal distribution is approximately <span class="math inline">\(\pm 1.96\)</span>, as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 両端から2.5%ずつ取り除くと</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.025</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.959964</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.959964</code></pre>
</div>
</div>
<p>When taken together, when the sample mean is <span class="math inline">\(\bar{X}\)</span>, the 95% confidence interval is obtained by multiplying the standard deviation by 1.96, as follows.</p>
<p><span class="math display">\[ \bar{X} - 1.96 \frac{\sigma}{\sqrt{n}} \le \mu \le \bar{X} + 1.96 \frac{\sigma}{\sqrt{n}} \]</span></p>
<p>The above expression in R and TeX code is a way of demonstrating the concept of a confidence interval. In simpler terms:</p>
<p>This equation represents how we estimate the range in which the true population mean (μ) falls, given our sample data.</p>
<p>The <span class="math inline">\(\bar{X}\)</span> signifies the mean (average) of our sample data.</p>
<p>The <span class="math inline">\(\sigma\)</span> represents the standard deviation of our sample data (how spread out the numbers are from their average value).</p>
<p>The <span class="math inline">\(n\)</span> is the number of data points in our sample.</p>
<p>1.96 is a value derived from the normal distribution that corresponds to a 95% confidence level (which is commonly used in statistical analysis).</p>
<p>So, in English - we can understand this formula as: “We are 95% confident that the true average of the entire population will fall somewhere between the value of <span class="math inline">\(\bar{X} - 1.96 \frac{\sigma}{\sqrt{n}}\)</span> and <span class="math inline">\(\bar{X} + 1.96 \frac{\sigma}{\sqrt{n}}\)</span>.”</p>
<p>Let’s apply the numerical example we just looked at and see for ourselves. We will find that the true value is included within the interval with almost 95% certainty.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>interval <span class="ot">&lt;-</span> <span class="fl">1.96</span> <span class="sc">*</span> SD <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>result.df2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">m =</span> m) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 推定が一致するとTRUE,外れるとFALSEになる変数を作る</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">interval_estimation =</span> <span class="fu">ifelse</span>(m <span class="sc">-</span> interval  <span class="sc">&lt;=</span> mu <span class="sc">&amp;</span> mu <span class="sc">&lt;=</span> m <span class="sc">+</span> interval, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> <span class="fu">mean</span>(interval_estimation)</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    prob
1 0.9498</code></pre>
</div>
</div>
</section>
<section id="confidence-interval-when-the-population-variance-of-the-normal-distribution-is-unknown" class="level3" data-number="6.8.2">
<h3 data-number="6.8.2" class="anchored" data-anchor-id="confidence-interval-when-the-population-variance-of-the-normal-distribution-is-unknown"><span class="header-section-number">6.8.2</span> Confidence Interval When the Population Variance of the Normal Distribution is Unknown</h3>
<p>In the previous example, we discussed a case where the population variance was known. However, if we know the population mean or variance, there’s no need to estimate them, practically speaking; instead, we often need to estimate when the population variance is unknown. Fortunately, in such cases - when we replace the population variance with the unbiased variance (sample statistic), it is known that the sample mean follows a t-distribution with degrees of freedom <span class="math inline">\(n-1\)</span>. (For more details, please refer to <span class="citation" data-cites="kosugi2023">小杉, 紀ノ定, and 清水 (<a href="#ref-kosugi2023" role="doc-biblioref">2023</a>)</span>) However, in this case, unlike the standard normal distribution where the 95% interval is confined to ±1.96, the shape of the t-distribution changes depending on the sample size. Therefore, this must be taken into account when calculating the confidence interval using the following formula. “Here, we are using this equation to express the range of a confidence interval.</p>
<p>In this formula:</p>
<ul>
<li><span class="math inline">\(\bar{X}\)</span> represents the sample mean,</li>
<li><span class="math inline">\(T_{0.025}\)</span> and <span class="math inline">\(T_{0.975}\)</span> are the lower and upper limits of the t-distribution respectively,</li>
<li><span class="math inline">\(U\)</span> stands for the standard deviation of the sample,</li>
<li><span class="math inline">\(n\)</span> is the number of observations or size of the sample,</li>
<li>And <span class="math inline">\(\mu\)</span> represents the population mean under the null hypothesis.</li>
</ul>
<p>Essentially, this formula says that, with 95% confidence, the true population mean (μ) lies within this range. As such, if the calculated interval contains the value of μ stated in the null hypothesis, we do not reject the null hypothesis. If it does not, we reject the null hypothesis.”</p>
<p>Here, <span class="math inline">\(T_{0.025}\)</span> refers to the 2.5 percentile of the t-distribution, and <span class="math inline">\(T_{0.975}\)</span> refers to the 97.5 percentile. The t-distribution is symmetric (assuming a mean of 0), so it’s reasonable to think of <span class="math inline">\(T_{0.025}=-T_{0.975}\)</span>. Moreover, <span class="math inline">\(U^2\)</span> is the unbiased variance (with <span class="math inline">\(U\)</span> being its square root).</p>
<p>Let’s confirm this with an approximate calculation using random numbers. Similarly, we can see that the true value is included within this interval at a close to 95% ratio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># シミュレーションの設定</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>iter <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>SD <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 平均値を格納しておくオブジェクト</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,iter)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>interval <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,iter)</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>iter) {</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># サンプリングし，標本統計量を保存</span></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>  sample <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> mu, <span class="at">sd =</span> SD)</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>  m[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample)</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>  U <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(sample)) <span class="co"># sd(sample)でも同じ</span></span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>  interval[i] <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p=</span><span class="fl">0.975</span>,<span class="at">df=</span>n<span class="dv">-1</span>) <span class="sc">*</span> U <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a>result.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">m =</span> m,<span class="at">interval =</span> interval) <span class="sc">%&gt;%</span></span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 推定が一致するとTRUE,外れるとFALSEになる変数を作る</span></span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">interval_estimation =</span> <span class="fu">ifelse</span>(m <span class="sc">-</span> interval <span class="sc">&lt;=</span> mu <span class="sc">&amp;</span> mu <span class="sc">&lt;=</span> m <span class="sc">+</span> interval, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb60-24"><a href="#cb60-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb60-25"><a href="#cb60-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb60-26"><a href="#cb60-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> <span class="fu">mean</span>(interval_estimation)</span>
<span id="cb60-27"><a href="#cb60-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    prob
1 0.9482</code></pre>
</div>
</div>
</section>
</section>
<section id="practice-problems-estimators-and-interval-estimation" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="practice-problems-estimators-and-interval-estimation"><span class="header-section-number">6.9</span> Practice Problems: Estimators and Interval Estimation</h2>
<ol type="1">
<li>We’ve demonstrated that the arithmetic mean <span class="math inline">\(M = \frac{1}{n}\sum x_i\)</span> is a consistent estimator, but what about the harmonic mean <span class="math inline">\(HM = \frac{n}{\sum \frac{1}{x_i}}\)</span> and the geometric mean <span class="math inline">\(GM = (\prod x_i)^{\frac{1}{n}} = \exp(\frac{1}{n}\sum \log(x_i))\)</span>? Let’s validate these through simulation.</li>
<li>Does the property that the sample mean approaches the population mean as the sample size <span class="math inline">\(n\)</span> increases, hold true for distributions other than the normal distribution? Let’s verify this using a simulation with the t-distribution with degrees of freedom <span class="math inline">\(\nu = 3\)</span>. Note that random numbers for the t-distribution can be generated using <code>rt()</code>, and if the non-centrality parameter <code>ncp</code> is not specified, its mean is 0.</li>
<li>It is known that when the degrees of freedom <span class="math inline">\(\nu\)</span> are extremely large in a t-distribution, it matches the standard normal distribution. Let’s use the <code>rt()</code> function to generate 1000 random numbers when the degrees of freedom are 10, 50, and 100, then draw their histograms to confirm their shapes. In addition, let’s calculate the average and standard deviation of these random numbers to verify that they approach the standard normal distribution.</li>
<li>Please generate 1000 random numbers from a normal distribution with a mean of 50 and a standard deviation of 10, then calculate the 95% confidence interval for the sample mean.</li>
<li>Please compare the widths of the 95% confidence interval for the sample mean, when the sample size is changed to 10, 100, and 1000, for a sample drawn from a normal distribution with a mean of 100 and a standard deviation of 15.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Sato1994-02-25" class="csl-entry" role="listitem">
佐藤坦. 1994. <em>はじめての確率論: 測度から確率へ</em>. 共立出版.
</div>
<div id="ref-Yoshida2021-02-25" class="csl-entry" role="listitem">
吉田伸生. 2021. <em>確率の基礎から統計へ</em>. 新装版. 日本評論社.
</div>
<div id="ref-kosugi2023" class="csl-entry" role="listitem">
小杉考司, 紀ノ定保礼, and 清水裕士. 2023. <em>数値シミュレーションで読み解く統計のしくみ〜Rでためしてわかる心理統計</em>. 技術評論社.
</div>
<div id="ref-Hiraoka200910" class="csl-entry" role="listitem">
平岡和幸, and 堀玄. 2009. <em>プログラミングのための確率統計</em>. オーム社. <a href="http://amazon.co.jp/o/ASIN/4274067750/">http://amazon.co.jp/o/ASIN/4274067750/</a>.
</div>
<div id="ref-Kono1999-05-01" class="csl-entry" role="listitem">
河野敬雄. 1999. <em>確率概論</em>. 京都大学学術出版会.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>For a more detailed discussion, see references such as <span class="citation" data-cites="Yoshida2021-02-25">吉田 (<a href="#ref-Yoshida2021-02-25" role="doc-biblioref">2021</a>)</span>, <span class="citation" data-cites="Kono1999-05-01">河野 (<a href="#ref-Kono1999-05-01" role="doc-biblioref">1999</a>)</span>, <span class="citation" data-cites="Sato1994-02-25">佐藤 (<a href="#ref-Sato1994-02-25" role="doc-biblioref">1994</a>)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>While we can’t provide firm evidence, it’s commonly said in colloquial terms as “the deceptive trio of five, three, and eight.” This suggests that when people are randomly stating numbers, the chances of using 5, 3, or 8 are higher than random chance would indicate.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter05.html" class="pagination-link  aria-label=" &lt;span="" with="" r&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Programming with R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter07.html" class="pagination-link" aria-label="<span class='chapter-number'>7</span>&nbsp; <span class='chapter-title'>The Logic and Errors of Statistical Hypothesis Testing</span>">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The Logic and Errors of Statistical Hypothesis Testing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>